#### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

In [4]:
s = np.arange(10)
t = np.flip(s)
t

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
d = np.diag(np.arange(2, 30, 5), k=0)
ds = np.flip(d, axis=None)
ds

array([[27,  0,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0,  0],
       [ 0,  0, 17,  0,  0,  0],
       [ 0,  0,  0, 12,  0,  0],
       [ 0,  0,  0,  0,  7,  0],
       [ 0,  0,  0,  0,  0,  2]])

In [6]:
np.sum(ds)

87

In [27]:
# np.diag(np.arange(2, 30, 5), k=0, axis=None)
# a = np.arange(10, axis=None)


In [78]:
np.flipud(d).diagonal(0)[::-1]

array([0, 0, 0, 0, 0, 0])

####  Задание 3
Решите систему уравнений:
4x + 2y + z = 4;
x + 3y = 12;
5y + 4z = -3.

In [7]:
from numpy import linalg

In [8]:
a = np.array( [ [1, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [9]:
linalg.solve(a, b)

array([ 2.33333333,  3.22222222, -4.77777778])

In [10]:
# проверка
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

#### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

Матрица в виде numpy array

In [12]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [21]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [76]:
x = []
y = []
for i, user in enumerate(users_stats):
    aLength = np.linalg.norm( next_user_stats )
    bLength = np.linalg.norm( user )
    cos = np.dot( next_user_stats, user ) / ( aLength * bLength )

    x.append(cos)
    y.append(user[0])
print(f'№: {x.index(max(x))}, ID: {y[x.index(max(x))]}, cosine: {round(max(x),2)}')
        

    

№: 7, ID: 0, cosine: 0.95


In [71]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [77]:
max_ = []
mav_vect = 0
for vect in users_stats:
    cosine(vect,  next_user_stats)
    if cosine(vect,  next_user_stats) > mav_vect:
        mav_vect = cosine(vect,  next_user_stats)
        max_ = vect
print(f'Наиболее похожий пользователь:{max_} cos={round(mav_vect, 2)}')

Наиболее похожий пользователь:[0 1 1 0 0 0] cos=0.95
